### ISSUE TITLE
HIT not displayed under requestor sandbox

### ISSUE THREAD

**Issue by abuvaneswari** [akuznets0v/mturk-lean-external-question#2]
Hi,

Nice demo code for MTurk external question!

I followed the instructions and got my HIT created in the sandbox today:
Your HIT has been created. You can see it at this link:
https://workersandbox.mturk.com/mturk/preview?groupId=3D8ERG8DI9S8SKJ7EJV1JIFBZVLAMP
Your HIT ID is: 3S8A4GJRD3T66ETU96AZ6T4BZY36VW

I was able to view, accept and submit this hit as a sandbox worker. 

But I am not able to view the HIT in the requester console under the 'manage' tab. 

I have asked Amazon MTurk for help. Meanwhile, if you have any idea why I am facing this issue, please share.  Sorry for posting this question under github->issues. This is probably not an issue with the code. 

Thanks,
Buvana

**Comment by akuznets0v** [comment]
Hi!

MTurk recently removed the ability to 'Manage HITS individually', which used to be the old way to preview all HITs posted, as well as download the results. For those features, you'll have to use the api.
